package io.ionic.starter.utils

object Constants {

  //String Constants
  const val CHANNEL_ID = "GIGA_SPEED_TEST"
  const val FOREGROUND_SERVICE_TAG = "GIGA_SPEED_TEST_SERVICE"
  const val FIRST_15_MIN = "FIRST_15_MIN"
  const val NEXT_SLOT = "NEXT_SLOT"
  const val SCHEDULE_TYPE = "SCHEDULE_TYPE"
  const val KEY_COUNTRY_CODE = "COUNTRY_CODE"
  const val KEY_SCHOOL_ID = "SCHOOL_ID"
  const val GIGA_APP_PREFERENCES = "GIGA_APP_PREFERENCES"
  const val KEY_FIRST_15_EXECUTED_TIME = "KEY_FIRST_15_EXECUTED_TIME"
  const val KEY_FIRST_15_SCHEDULED_TIME = "KEY_FIRST_15_SCHEDULED_TIME"
  const val KEY_LAST_EXECUTION_DAY = "KEY_LAST_EXECUTION_DAY"
  const val KEY_LAST_SLOT_EXECUTION_HOUR = "KEY_LAST_SLOT_EXECUTION_HOUR"

  // Numeric Constants
  const val NOTIFICATION_ID = 101
}
